version: '2.3'

services:
  mysql1:
    image: mysql:8.0
    container_name: mysql-cloner-db1
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"status", "-h", "localhost", "-u", "root", "-psecret" ]
      start_period: 2s
      timeout: 3s
      interval: 2s
      retries: 10
  mysql2:
    image: mysql:8.0
    container_name: mysql-cloner-db2
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db2
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"status", "-h", "localhost", "-u", "root", "-psecret" ]
      start_period: 2s
      timeout: 3s
      interval: 2s
      retries: 10
  cloner:
    build: .
    container_name: mysql-cloner-sample
    depends_on:
      mysql1:
        condition: service_healthy
      mysql2:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql1
      MYSQL_PORT: "3306"
      MYSQL_USER: root
      MYSQL_PASS: secret
      MYSQL_DATABASE: db1
      TARGET_MYSQL_HOST: mysql2
      TARGET_MYSQL_PORT: "3306"
      TARGET_MYSQL_USER: root
      TARGET_MYSQL_PASS: secret
      TARGET_MYSQL_DATABASE: db2
